set -g set-clipboard on
set -g detach-on-destroy off
set-option -g default-terminal "tmux-256color"
# set -ga terminal-overrides ',xterm*:Ms=\E]52;c;%p2%s\7'
# set -ga terminal-overrides ',xterm-kitty:Ms=\E]52;c;%p2%s\7'
# set -ga terminal-overrides ',wezterm:Ms=\E]52;c;%p2%s\7'
set -ga terminal-overrides ",*:Tc"
set -s escape-time 0
set -g buffer-limit 200

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
set -g base-index 1

#  bind -n M-s display-popup -E "sesh picker"
bind -n M-w display-popup -E "tms windows"

set-window-option -g mode-keys vi
bind-key -n M-v copy-mode # additional binding to default prefix+[
bind -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# fast windows
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind g display-popup -d "#{pane_current_path}" -xC -yC -w95% -h95% -E "lazygit"

# fun and fancy dynamic window renaming
# set -g automatic-rename on
# set -g automatic-rename-format '#{?@semantic_name,#{@semantic_name:} ,}#{pane_current_command}@#{b:pane_current_path}'
# bind-key , command-prompt -p "semantic name:" "set-window-option -w @semantic_name '%%'"
# bind-key r set-window-option -wu @semantic_name

bind-key -n M-s run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-u:unix-line-discard,ctrl-k:kill-line' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~/source ~/git ~/ws/percv_workspace)'
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \

    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""
