format = """
$cmd_duration\
$username\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$sudo\
$directory\
$character\
"""

right_format = """
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$python\
$rlang\
$rust\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$azure\
$crystal\
$custom\
$jobs\
$status\
$os\
$battery\
$time\
"""

add_newline = false

[character]
format = " $symbol "
# success_symbol = "[\\$](bold green)"
success_symbol = "[](bold italic bright-yellow)"
error_symbol = "[⊘](italic red)"

[env_var.VIMSHELL] # vim subshell
# symbol = ""
symbol = "v"
format = "[$env_value]($style)"
style = 'purple bold italic'

[sudo]
format = "[$symbol]($style)"
style = "bold bright-red"
symbol = "SUDO"
disabled = true

[username]
style_user = "bold bright-black "
style_root = "purple bold italic"
format = "[$user]($style)"
disabled = true

[hostname]
format = "[@$hostname: ]($style)"
style = "italic green"

[directory]
home_symbol = "~"
truncation_length = 3
truncation_symbol = "/"
read_only = "  "
style = "italic bold"
format = '[$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
min_time = 500
format = "[$duration ](italic purple)"
# format = "[$duration ](italic bright-yellow)"

[jobs]
format = "[ $symbol$number]($style)"
style = "white"

[localip]
ssh_only = true
disabled = true

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "[█](italic green)"
charging_symbol = "[↑](italic green)"
discharging_symbol = "[↓](italic)"
unknown_symbol = "[░](italic)"
empty_symbol = "[▃](italic red)"

[[battery.display]]
threshold = 40
style = "dimmed yellow"

[[battery.display]]
threshold = 70
style = "dimmed white"

[git_branch]
format = "[$symbol$branch(:$remote_branch) ]($style)"
symbol = "[](bold italic red)"
# symbol = "[](bold italic bright-red)"
style = "bold italic bright-black"
# style = "bold italic bright-white"

[git_commit]
format = "[\\($hash$tag\\)]($style)"
style = "white"

[git_state]
style =	"bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"	
revert = "revert"	
cherry_pick = "cherry"
bisect = "bisect"	
am = "am"	
am_or_rebase = "am/rebase"

[git_status]
style = "white"
format = """([⎪$ahead$behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"""
ahead = "⇡${count}(italic green)"
behind = "⇣${count}(italic red)"
staged = "[${count}](italic bright-green)" 
modified = "[~${count}](italic bright-yellow)" 
deleted =  "[✕${count}](italic bright-red)" 
untracked = "[?${count}](italic bright-black)" 
conflicted =  "[${count}~](italic bright-magenta)" 
stashed = "[${count}*](italic white)" 
# stashed = "[◦◫◦](italic white)"
# modified = "[●◦](italic yellow)"
# conflicted = "[◪◦](italic bright-magenta)"
# ahead = "[↑│[${count}](bold white)│](italic green)"
# behind = "[↓│[${count}](bold white)│](italic red)"
# diverged = "[◇ ▲┤[${ahead_count}](regular white)│▽┤[${behind_count}](regular white)│](italic bright-magenta)"
# untracked = "[◌◦](italic bright-yellow)"
# staged = "[■┤[$count](bold white)│](italic bright-cyan)"
# renamed = "[◎◦](italic bright-blue)"
# deleted = "[✕](italic red)"

[python]
symbol = ""
format = "[ ${symbol} ${version}]($style)"
version_format = "${major}.${minor}"
style = "italic bright-black"
